version: '3.8'
services:


  frontend:
    build:
      context: ./ng-stamina
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
    - ./ng-stamina:/app
    - /app/node_modules
    depends_on:
      - auth
      - users

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:auth:dev
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb
      - rabbitmq

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:users:dev
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/users/.env
    depends_on:
      - mongodb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongodb_data:
