services:
  frontend:
    build:
      context: ./ng-stamina
      dockerfile: Dockerfile
      target: development
    ports:
      - '4200:4200'
    volumes:
      - ./ng-stamina:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - auth
      - users

  auth:
    build:
      context: ./nest-stamina
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:auth:dev
    ports:
      - '3001:3001'
    volumes:
      - ./nest-stamina/apps/auth/src:/usr/src/app/apps/auth/src
      - ./nest-stamina/libs:/usr/src/app/libs
    env_file:
      - ./nest-stamina/apps/auth/.env
    depends_on:
      - rabbitmq

  users:
    build:
      context: ./nest-stamina
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:users:dev
    ports:
      - '3002:3002'
    volumes:
      - ./nest-stamina/apps/users/src:/usr/src/app/apps/users/src
      - ./nest-stamina/libs:/usr/src/app/libs
    env_file:
      - ./nest-stamina/apps/users/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
