FROM node:18-alpine AS development

WORKDIR /usr/src/app

# Copy dependency files
COPY package*.json ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build the application
RUN npm run build auth

EXPOSE 3001 9229

CMD ["npm", "run", "start:auth:dev"]